# Generated by Django 4.2.3 on 2023-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cart_total_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
